# data
data:
  instruct_data: "/Users/Andres.DESKTOP-D77KM25/Documents/Legal_tech_projects/Mistral-Finetune/mistral-finetune/data/ultrachat_chunk_train.jsonl"  # Fill
  data: ""  # Optionally fill with pretraining data 
  eval_instruct_data: "/Users/Andres.DESKTOP-D77KM25/Documents/Legal_tech_projects/Mistral-Finetune/mistral-finetune/data/ultrachat_chunk_eval.jsonl"  # Optionally fill

# model
model_id_or_path: "/Users/Andres.DESKTOP-D77KM25/Documents/Legal_tech_projects/Mistral-Finetune/mistral-finetune/mistral_models/7B-v0.3"
lora:
  rank: 64

# optim
seq_len: 32768
batch_size: 1
max_steps: 300
optim:
  lr: 6.e-5
  weight_decay: 0.1
  pct_start: 0.05

# other
seed: 0
log_freq: 1
eval_freq: 100
no_eval: False
ckpt_freq: 100

save_adapters: True  # save only trained LoRA adapters. Set to `False` to merge LoRA adapter into the base model and save full fine-tuned model

run_dir: ""  # Fill

wandb:
  project: null # your wandb project name
  run_name: None # your wandb run name
  key: "5aea76c1bd3c56d5e6b11da06882572d44bde7f6" # your wandb api key
  offline: False
