name: mistral-finetune
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - cudatoolkit=11.8
  - pip:
    - torch==2.2.0
    - triton==2.2.0
    - xformers==0.0.24
    - fire
    - simple-parsing
    - pyyaml
    - mistral-common>=1.3.1
    - safetensors
    - tensorboard
    - tqdm 