batch_size: 1
ckpt_freq: 100
data:
  data: null
  eval_instruct_data: /Users/Andres.DESKTOP-D77KM25/Documents/Legal_tech_projects/Mistral-Finetune/mistral-finetune/data/ultrachat_chunk_eval.jsonl
  instruct_data: /Users/Andres.DESKTOP-D77KM25/Documents/Legal_tech_projects/Mistral-Finetune/mistral-finetune/data/ultrachat_chunk_train.jsonl
eval_freq: 200
log_freq: 1
lora:
  rank: 64
max_steps: 100
model_id_or_path: C:\Users\Andres.DESKTOP-D77KM25\Documents\Legal_tech_projects\Mistral-Finetune\mistral-finetune\mistral_models\7B-v0.3
no_eval: false
num_microbatches: 8
optim:
  lr: 1.0e-05
  pct_start: 0.05
  weight_decay: 0.1
run_dir: C:\Users\Andres.DESKTOP-D77KM25\Documents\Legal_tech_projects\Mistral-Finetune\mistral-finetune\mistral_models\test_ultra
save_adapters: true
seed: 0
seq_len: 8192
